### ISSUE TITLE
Gracefully handle rules containing invalid search conditions

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/sigma-go#14]
Currently sigma-go panics when given a rule that looks like this:
```yaml
detection:
    someCondition:
        foo: bar
    condition: nonExistentCondition
```

This panic happens here: https://github.com/bradleyjkemp/sigma-go/blob/fe36bd7f61b78a9aafb7c7e705b1ba2a196da313/evaluator/evaluate_search.go#L41

Instead this function should be extended so that it can return an error back to the caller

**Comment by veramine** [comment]
I hit this on a sigma project rule with the following definition:

```
detection:
    selection:
        Image|endswith: '\3proxy.exe'
    selection_pe:
        Description: '3proxy - tiny proxy server'
    selection_params: # param combos seen in the wild
        CommandLine|contains: '.exe -i127.0.0.1 -p'
    condition: 1 of selection
```
Error was:

```
panic: unhandled node type sigma.OneOfIdentifier

goroutine 9 [running]:
github.com/bradleyjkemp/sigma-go/evaluator.RuleEvaluator.evaluateSearchExpression({{{0x14000639e70, 0xc}, {{0x140008de4f0, 0x10}, {0x140008de5a0, 0x7}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...}, ...)
	/Users/jness/v/onprem/pkg/mod/github.com/bradleyjkemp/sigma-go@v0.4.2/evaluator/evaluate_search.go:83 +0x314
github.com/bradleyjkemp/sigma-go/evaluator.RuleEvaluator.Matches({{{0x14000639e70, 0xc}, {{0x140008de4f0, 0x10}, {0x140008de5a0, 0x7}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...}, ...)
	/Users/jness/v/onprem/pkg/mod/github.com/bradleyjkemp/sigma-go@v0.4.2/evaluator/evaluate.go:109 +0x2e8
```

I'll file an issue on the Sigma project rule:  https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_3proxy_usage.yml
