### ISSUE TITLE
Error parsing "related" with a map of id and type

### ISSUE THREAD

**Issue by veramine** [bradleyjkemp/sigma-go#19]
I'm testing the latest sigma-go and it seems to be expecting the "related" key word to be followed by a string.  But some rules have a map here.  

```
% ./sigmatest proc_creation_win_apt_chafer_mar18.yml
2022/09/19 13:53:06 yaml: unmarshal errors:
  line 4: cannot unmarshal !!map into string
```

```
% head -5 proc_creation_win_apt_chafer_mar18.yml
title: Chafer Activity
id: ce6e34ca-966d-41c9-8d93-5b06c8b97a06
related:
    - id: 53ba33fd-3a50-4468-a5ef-c583635cfa92
      type: derived
```

https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_apt_chafer_mar18.yml

[proc_creation_win_apt_chafer_mar18.txt](https://github.com/bradleyjkemp/sigma-go/files/9602316/proc_creation_win_apt_chafer_mar18.txt)
