### ISSUE TITLE
invalid token '*' in certain condition strings

### ISSUE THREAD

**Issue by veramine** [bradleyjkemp/sigma-go#20]
Could not parse this one:
```
detection:
  selection1:
    CommandLine|contains: 'setup0.exe -p'
  selection2a:
    CommandLine|contains: 'setup.exe'
  selection2b:
    CommandLine|endswith:
      - '-x:0'
      - '-x:1'
      - '-x:2'
  condition: selection1 or all of selection2*
```

invalid token '*'

https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_apt_winnti_pipemon.yml

**Comment by veramine** [comment]
This parses fine:  

```condition: selection1 or all of selection*```

but this doesn't parse:

```  condition: selection1 or all of selection2*```

**Comment by twsnmp** [comment]
Same issue as #41.

If there is a number in front of the *, this error occurs.

The fix for #41 solves this error.

**Comment by twsnmp** [comment]
An alternative is to change it so that the * is not preceded by a number, as shown below.

```yaml
detection:
  selection_a:
    CommandLine|contains: 'setup0.exe -p'
  selection_b_a:
    CommandLine|contains: 'setup.exe'
  selection_b_b:
    CommandLine|endswith:
      - '-x:0'
      - '-x:1'
      - '-x:2'
  condition: selection_a or all of selection_b_*
```
