### ISSUE TITLE
Rules fail to evaluate when there are multiple mappings for the same field

### ISSUE THREAD

**Issue by lmoz25** [bradleyjkemp/sigma-go#26]
As demonstrated in https://github.com/bradleyjkemp/sigma-go/pull/25, the rule parser fails to find a match if a rule evaluator has multiple field mappings for one field, e.g if `RuleEvaluator.fieldmappings` looks like
```
"FieldToEval": ["$.payload.something.field", "$.payload.another.field"]
```

then the rule 
```
detection:
    thingToMatch:
        FieldToEval: value
    condition: thingToMatch
```
will fail to match on an event like
```
{
    "payload": {
        "something": {
            "field": "value"
        }
    }
}
```

It _looks_ like the library is supposed to be able to support multiple mappings for the same field, but if not then feel free to ignore.
