### ISSUE TITLE
Error parsing detections with list of maps

### ISSUE THREAD

**Issue by pathtofile** [bradleyjkemp/sigma-go#9]
Hey mate, super appreciative of this library, I've just discovered it fails to parse some rules from the official Sigma repo, e.g. [this one](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_pc_enumeration_for_credentials_in_registry.yml). It erorrs out with `cannot unmarshal !!map into string`.

I am super new to SIGMA rules, but digging into it, the issue could possibly be that looking at [the spec](https://github.com/SigmaHQ/sigma/wiki/Specification#search-identifier) can be lists of maps. E.g. this basic rules fails to be parsed by sigma-go but according the spec it is valid (with the `CommandLine` being logical OR'd together):
```
title: Test that doesn't work
id: e0b0c2ab-3d52-46d9-8cb7-049dc775fbd1
status: experimental
description: A Sigma rule that fails to parse using sigma-go
author: pathtofile
date: 2022/01/23
logsource:
    category: process_creation
    product: windows
level: high
detection:
    baddetect:
        - CommandLine|contains: 'apple'
        - CommandLine|contains: 'bannana'
    condition: baddetect
```

**Comment by pathtofile** [comment]
Error I think is coming from here: https://github.com/bradleyjkemp/sigma-go/blob/main/rule_parser.go#L88

**Comment by bradleyjkemp** [comment]
Thanks for raising this, this is a very interesting case!

According to [the text specification](https://github.com/SigmaHQ/sigma/wiki/Specification#detection), a detection can **either** be:
* A list of string keywords
* A map of filednames to values

This is backed up by [the yaml schema](https://github.com/SigmaHQ/sigma/wiki/Specification#rx-yaml):
```
detection:
    // ... omitted for brevity
    rest:
        type: //any
        of:
            - type: //arr
              contents: //str
            - type: //map
              values:
                  type: //any
                  of:
                      - type: //str
                      - type: //arr
                        contents: //str
                        length:
                            min: 2
```

*However*, it's reasonable to argue that `sigmac` should be the source of truth for what's a valid rule, not the text specification 🙂 

Unfortunately, I'm not sure how easily this could be supported in `sigma-go`. I'm also unsure it's a good feature to support. Your example can trivially be rewritten as:
```yaml
baddetect:
    CommandLine|contains:
        - 'apple'
        - 'banana'
```
And more complex examples can be split out into e.g.
```yaml
baddetect-1:
    CommandLine|contains: 'apple'
baddetect-2:
    CommandLine|contains: 'banana'
```
with a condition using `(any of baddetect-*)`

So for now, I'm inclined to intentionally not support this case (unless in future we find a compelling example where a list of maps really is the best way to write a rule)?
